spring:
  datasource:
    url: jdbc:mysql://localhost:3306/2023Web?   useUnicode=true&characterEncoding=utf8
    username: root
    password: WSG13654462493
    driver-class-name: com.mysql.cj.jdbc.Driver
